### PR TITLE
PHOENIX-6253 Change shaded connector jar naming convention

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   3m  9s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   8m 41s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  22m 50s |  master passed  |
| +1 :green_heart: |  compile  |   3m 50s |  master passed  |
| +1 :green_heart: |  javadoc  |   2m 29s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 20s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  20m 16s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 29s |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 29s |  the patch passed  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 2 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  xml  |   0m 12s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m 19s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  13m 35s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   1m  0s |  The patch does not generate ASF License warnings.  |
|  |   |  82m  9s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-45/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix-connectors/pull/45 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux fd410b3f225e 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-connectors-personality.sh |
| git revision | master / 22fe0ce |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| whitespace | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-45/1/artifact/yetus-general-check/output/whitespace-eol.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-45/1/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-45/1/testReport/ |
| Max. process+thread count | 1650 (vs. ulimit of 30000) |
| modules | C: phoenix-hive-base phoenix-pig-base phoenix-kafka-base phoenix-spark-base phoenix4-connectors-assembly phoenix5-connectors-assembly . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-45/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 32s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |  10m 20s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  17m 19s |  master passed  |
| +1 :green_heart: |  compile  |   2m 15s |  master passed  |
| +1 :green_heart: |  javadoc  |   2m 20s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 19s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  17m  2s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 23s |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 23s |  the patch passed  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  xml  |   0m 12s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m 29s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  10m 17s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 58s |  The patch does not generate ASF License warnings.  |
|  |   |  67m 26s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-45/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix-connectors/pull/45 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux 8acdac3e4279 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-connectors-personality.sh |
| git revision | master / aff86a2 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| whitespace | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-45/2/artifact/yetus-general-check/output/whitespace-eol.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-45/2/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-45/2/testReport/ |
| Max. process+thread count | 1707 (vs. ulimit of 30000) |
| modules | C: phoenix-hive-base phoenix-pig-base phoenix-kafka-base phoenix-spark-base phoenix4-connectors-assembly phoenix5-connectors-assembly . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-45/2/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by joshelser — COMMENTED** [review]
For those who rely on the naming of the jars we created (in a specific location), this is a breaking change.

We could either call this out in the 5.1.0 release as a breaking change (and add some documentation for users so they know which jar they want to use) or we add some more symlinks to put in the old jar names.

I think the former is easier long-term. WDYT?

**Comment by stoty** [comment]
I think that we are breaking much more than this already, even without this patch.

- We have completely removed the connectors from Phoenix proper, and moved them to a new project, so both the old maven coordinates, and the installed JAR locations are gone anyways.
- All but the hive connectors were included in the phoenix-client JAR, and we told users to use that. The new phoenix-client JAR doesn't include them for obvious reasons, and I currently have no plans reintroduce a new uber-uber-jar to connectors, due to the shading issues that the old one has. (see PHOENIX-5202 )

We will need update ALL connectors-related docs anyways.
- Add a release note for core that points to the new -connectors (and -pqs repos)
- Add/Update building docs for PQS and connectors, describing how the 4.x/master, Phoenix and HBase releases are handled.
- Update the docs for each connector for the new repo and JARs / artifacts. 
- The Spark connectors docs just plain don't work as written, and possibly never did.
- The Hive connector has serious conflicts with the HBase 2.0.0-alpha included in Hive 3.1.2 (and also with the ancient Hbase in 2.4 for Phoenix 4.x), which requires either hacking up the binary hive distro, or rebuilding it from source with an unmerged patch (see  HIVE-24473), we'll also have to document that.

However, I am not completely sure about the exact naming scheme in this PR, so if you'd prefer an alternative, I'd be happy to discuss that, even if keeping the old one is impossible.

**Comment by joshelser** [comment]
> However, I am not completely sure about the exact naming scheme in this PR, so if you'd prefer an alternative, I'd be happy to discuss that, even if keeping the old one is impossible.

Ah, that's a good point. I forgot that we don't have an official release of this yet. Ship it.

**Review by joshelser — APPROVED** [review]

**Pull request closed without merging**
