### PR TITLE
PHOENIX-7308 Remove duplicate declarations of hbase-endpoint d…

### PR DESCRIPTION
**Pull request by anchal246**
…ependency in pom.xml of module phoenix5-hive-shaded

### CODE REVIEW

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   5m 22s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 13s |  root in master failed.  |
| -1 :x: |  compile  |   6m 50s |  phoenix5-hive-shaded in master failed.  |
| -1 :x: |  javadoc  |   0m  8s |  phoenix5-hive-shaded in master failed.  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m  7s |  root in the patch failed.  |
| -1 :x: |  compile  |   0m  8s |  phoenix5-hive-shaded in the patch failed.  |
| -1 :x: |  javac  |   0m  8s |  phoenix5-hive-shaded in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   0m  8s |  phoenix5-hive-shaded in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 10s |  phoenix5-hive-shaded in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 17s |  The patch does not generate ASF License warnings.  |
|  |   |  13m 40s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix-connectors/pull/146 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux 8f91ef8e3afd 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-connectors-personality.sh |
| git revision | master / 8adb127 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/1/artifact/yetus-general-check/output/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/1/artifact/yetus-general-check/output/branch-compile-phoenix5-hive-shaded.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/1/artifact/yetus-general-check/output/branch-javadoc-phoenix5-hive-shaded.txt |
| mvninstall | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/1/artifact/yetus-general-check/output/patch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/1/artifact/yetus-general-check/output/patch-compile-phoenix5-hive-shaded.txt |
| javac | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/1/artifact/yetus-general-check/output/patch-compile-phoenix5-hive-shaded.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/1/artifact/yetus-general-check/output/patch-javadoc-phoenix5-hive-shaded.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/1/artifact/yetus-general-check/output/patch-unit-phoenix5-hive-shaded.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/1/testReport/ |
| Max. process+thread count | 52 (vs. ulimit of 30000) |
| modules | C: phoenix5-hive-shaded U: phoenix5-hive-shaded |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by szucsvillo — CHANGES_REQUESTED** [review]
It looks like the dependency is still duplicated in several other modules. It would be great to remove those duplicates as well for consistency. 
Also, don't forget to include the JIRA ticket number in the commit message. Thanks!

**Comment by anchal246** [comment]
> It looks like the dependency is still duplicated in several other modules. It would be great to remove those duplicates as well for consistency. Also, don't forget to include the JIRA ticket number in the commit message. Thanks!

Thanks for bringing this to my attention . I've updated the pr.

**Review by szucsvillo — APPROVED** [review]

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 11s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |  15m 34s |  Maven dependency ordering for branch  |
| -1 :x: |  mvninstall  |   0m  9s |  root in master failed.  |
| -1 :x: |  compile  |   0m 12s |  phoenix5-hive4-shaded in master failed.  |
| -1 :x: |  compile  |   0m 10s |  phoenix5-hive-shaded in master failed.  |
| -1 :x: |  compile  |   0m 11s |  phoenix5-spark3-shaded in master failed.  |
| -1 :x: |  compile  |   0m  9s |  phoenix5-spark-shaded in master failed.  |
| -1 :x: |  javadoc  |   0m  8s |  phoenix5-hive4-shaded in master failed.  |
| -1 :x: |  javadoc  |   0m  8s |  phoenix5-hive-shaded in master failed.  |
| -1 :x: |  javadoc  |   0m  7s |  phoenix5-spark3-shaded in master failed.  |
| -1 :x: |  javadoc  |   0m  7s |  phoenix5-spark-shaded in master failed.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 11s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   0m  7s |  root in the patch failed.  |
| -1 :x: |  compile  |   0m  8s |  phoenix5-hive4-shaded in the patch failed.  |
| -1 :x: |  compile  |   0m  8s |  phoenix5-hive-shaded in the patch failed.  |
| -1 :x: |  compile  |   0m  7s |  phoenix5-spark3-shaded in the patch failed.  |
| -1 :x: |  compile  |   0m  8s |  phoenix5-spark-shaded in the patch failed.  |
| -1 :x: |  javac  |   0m  8s |  phoenix5-hive4-shaded in the patch failed.  |
| -1 :x: |  javac  |   0m  8s |  phoenix5-hive-shaded in the patch failed.  |
| -1 :x: |  javac  |   0m  7s |  phoenix5-spark3-shaded in the patch failed.  |
| -1 :x: |  javac  |   0m  8s |  phoenix5-spark-shaded in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  6s |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   0m  8s |  phoenix5-hive4-shaded in the patch failed.  |
| -1 :x: |  javadoc  |   0m  8s |  phoenix5-hive-shaded in the patch failed.  |
| -1 :x: |  javadoc  |   0m  7s |  phoenix5-spark3-shaded in the patch failed.  |
| -1 :x: |  javadoc  |   0m  8s |  phoenix5-spark-shaded in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m  8s |  phoenix5-hive4-shaded in the patch failed.  |
| -1 :x: |  unit  |   0m  8s |  phoenix5-hive-shaded in the patch failed.  |
| -1 :x: |  unit  |   0m  7s |  phoenix5-spark3-shaded in the patch failed.  |
| -1 :x: |  unit  |   0m  8s |  phoenix5-spark-shaded in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 38s |  The patch does not generate ASF License warnings.  |
|  |   |  20m 14s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix-connectors/pull/146 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux c1e3fc3f4d2f 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-connectors-personality.sh |
| git revision | master / 8adb127 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/branch-compile-phoenix5-hive4-shaded.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/branch-compile-phoenix5-hive-shaded.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/branch-compile-phoenix5-spark3-shaded.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/branch-compile-phoenix5-spark-shaded.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/branch-javadoc-phoenix5-hive4-shaded.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/branch-javadoc-phoenix5-hive-shaded.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/branch-javadoc-phoenix5-spark3-shaded.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/branch-javadoc-phoenix5-spark-shaded.txt |
| mvninstall | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-compile-phoenix5-hive4-shaded.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-compile-phoenix5-hive-shaded.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-compile-phoenix5-spark3-shaded.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-compile-phoenix5-spark-shaded.txt |
| javac | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-compile-phoenix5-hive4-shaded.txt |
| javac | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-compile-phoenix5-hive-shaded.txt |
| javac | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-compile-phoenix5-spark3-shaded.txt |
| javac | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-compile-phoenix5-spark-shaded.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-javadoc-phoenix5-hive4-shaded.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-javadoc-phoenix5-hive-shaded.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-javadoc-phoenix5-spark3-shaded.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-javadoc-phoenix5-spark-shaded.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-unit-phoenix5-hive4-shaded.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-unit-phoenix5-hive-shaded.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-unit-phoenix5-spark3-shaded.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/artifact/yetus-general-check/output/patch-unit-phoenix5-spark-shaded.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/testReport/ |
| Max. process+thread count | 52 (vs. ulimit of 30000) |
| modules | C: phoenix5-hive4-shaded phoenix5-hive-shaded phoenix5-spark3-shaded phoenix5-spark-shaded U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-146/2/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by stoty — APPROVED** [review]
+1 LGTM

**Pull request merged**
