### PR TITLE
PHOENIX-6098 IndexPredicateAnalyzer wrongly handles pushdown predicat…

### PR DESCRIPTION
**Pull request by brfrn169**
…es and residual predicates

### CODE REVIEW

**Comment by stoty** [comment]
You're going to need to rebase this for the tests to pass, to get the changes from Phoenix-6100, @brfrn169

**Comment by ankitsinghal** [comment]
It seems HIVE-11398 introduced the change where GenericUDFOPAnd can expect more than 2 arguments but Phoenix still uses Hive 1.2.1 version(https://github.com/apache/phoenix-connectors/blob/master/pom.xml#L75) which doesn't have this change. so is the problem really can affect us?

**Comment by stoty** [comment]
@richardantal has recently resurrected the Hive 3 connector from the old master branch with various fixes, 
and is working on backporting it  to Hive 2 for 4.x. 
So even if this is not relevant for the old Hive 1 connector in phoenix-connectors, I think that it is still needed for the new Hive3/Hive2 connector.

**Comment by ankitsinghal** [comment]
yes, that makes sense, thanks @stoty  for clarification, I didn't know that we have Hive3 connector separately. Changes look good to me for phoenix-hive3 (and for hive2 in 4.x branch) @brfrn169

**Comment by brfrn169** [comment]
@ankitsinghal @stoty Ah, okay. Thank you for pointing that out. I will modify this patch and apply the fix to phoenix-hive3.

**Comment by ankitsinghal** [comment]
+1, 

@richardantal , should we have a backport ticket for this?

**Comment by richardantal** [comment]
@ankitsinghal It is not necessary if the same code works, because the common part will be unified to reduce code duplication. I am currently working on it.

**Pull request closed without merging**
