### PR TITLE
PHOENIX-6667 Spark3 connector requires that all columns are specified…

### PR DESCRIPTION
**Pull request by stoty**
… when writing

also fixes PHOENIX-6668 Spark3 connector cannot distinguish column name cases

### CODE REVIEW

**Comment by stoty** [comment]
Attila's patch fixed and squashed, for CI purposes.

**Comment by stoty** [comment]
The failures are all all unrelated, in fact all tests have passed.
Unfortunately, the CI doesn't even run the scala tests that would appy ATM, but they have passed locally.

**Comment by stoty** [comment]
@attilapiros this is the modified version

**Review by richardantal — APPROVED** [review]
LGTM, tests passed locally for me too

**Pull request closed without merging**
