### PR TITLE
PHOENIX-6632 Migrate connectors to spark-3

### PR DESCRIPTION
**Pull request by stoty**
Co-authored-by: Istvan Toth <stoty@apache.org>

### CODE REVIEW

**Comment by stoty** [comment]
I am aware that this change is next to unreviewable.

The original change, https://github.com/apache/phoenix-connectors/pull/69 is much more readable.

This one is heavily based on the original PR, with the following changes:
* Moved to a new maven module
* Split tests to a separate maven module
* Minor fixes
* Changed the java package to better mach Spark3
* Changed / disabled scala tests according to the lost functionality in Spark3

**Comment by richardantal** [comment]
I've started to review this change and the original #69 .

I ran a `mvn verify` with the scala test and it seems to be okey.
I haven't finished the review yet but I think we should add the new phoenix5-spark3 artifact to the assembly.

**Comment by ashwinb1998** [comment]
Awesome, thanks Istvan.

**Comment by ashwinb1998** [comment]
@stoty Would it be possible to link my Github profile to this PR instead of just my name? 
I'm asking because my profile is not added to the list of contributors in this repository

**Comment by stoty** [comment]
The best I can think of is an addendum with the right author info. @ashwinb1998 
If you make another PR with a title similar to:

**PHOENIX-6632 Migrate connectors to spark-3 (addendum: add author's preferred identity)**

and set the athor to your preferred identity, for some whitesapce/formatting change,
I wil commit to the repo, so that your preferred identity is also shown.

**Comment by stoty** [comment]
As discussed privately, there is no way to change the linked github profile for existing commits.

**Comment by richardantal** [comment]
@stoty I think this PR can be closed as you already merged the change

**Pull request closed without merging**
