### PR TITLE
PHOENIX-6163 Move CI to ASF Jenkins for connectors

### PR DESCRIPTION
**Pull request by stoty**
add .asf.yaml
    update ASF maven parent to 23
    add spotbugs reporting
    copy and adapt postcommit job from core
    copy and adapt Github PR precommit job from core

### CODE REVIEW

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   0m  3s |  Dockerfile '/home/jenkins/jenkins-agent/workspace/ectors-PreCommit-GitHub-PR_PR-32/yetus-general-check/src/dev/docker/Dockerfile.yetus' not found.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/phoenix-connectors/pull/32 |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-32/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
This is now on par with solution in core, including all addendums.

**Comment by richardantal** [comment]
I see that most of this change has been copied from Phoenix core, it seems to be well adapted to Phoenix-connectors.
I found some comments that could be updated as well, in dev/jenkins_precommit_github_yetus.sh line num 71 and dev/phoenix-connectors-personality.sh 142, 143? 207, 232, 253.
Otherwise this change looks good to me.

**Comment by stoty** [comment]
Thank you. I have updated the comments.

**Pull request closed without merging**
