### PR TITLE
PHOENIX-5787 Do not package hive dependencies into phoenix-hive jar

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Review by joshelser — APPROVED** [review]
Assuming you tested this out (I don't think we have automated tests which would validate the change), +1

**Comment by stoty** [comment]
Thank you Josh.

I have run an e2e test on Phoenix 5, but not on Phoenix 4, which should be very similar classpath-wise.

We still have the HBase version conflict problem outlined in the ticket, but we've always had that, but we cannot solve that from our side.

**Comment by stoty** [comment]
I found out before committing, that due what is probably a maven bug, it is not possible to do a full build with this patch.

The new patch removes the feature that limits the build to the phoenix4 or phoenix5 connectors by specifying a profile, as that makes it impossible to order the modules in a sequence that doesn't trigger the maven bug.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  6s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   8m 14s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 16s |  master passed  |
| +1 :green_heart: |  compile  |   2m 40s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 22s |  master passed  |
| -1 :x: |  javadoc  |   0m 13s |  phoenix5-connectors-assembly in master failed.  |
| +0 :ok: |  spotbugs  |   5m 13s |  root in master has 116 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   1m 35s |  phoenix-hive-base in master has 46 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   0m 46s |  phoenix-hive-base/phoenix4-hive in master has 46 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   0m 47s |  phoenix-hive-base/phoenix5-hive in master has 45 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 31s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  12m 44s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m  3s |  the patch passed  |
| +1 :green_heart: |  javac  |   3m  3s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m 28s |  root: The patch generated 103 new + 0 unchanged - 0 fixed = 103 total (was 0)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  7s |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   1m  0s |  root generated 6 new + 14 unchanged - 6 fixed = 20 total (was 20)  |
| +1 :green_heart: |  spotbugs  |   9m 47s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  54m  9s |  root in the patch failed.  |
| -1 :x: |  asflicense  |   0m 41s |  The patch generated 2 ASF License warnings.  |
|  |   | 116m 54s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.hive.query.PhoenixQueryBuilderTest |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/5/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix-connectors/pull/42 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile spotbugs hbaseanti checkstyle |
| uname | Linux 3a5388dbd410 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-connectors-personality.sh |
| git revision | master / 234ed7c |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/5/artifact/yetus-general-check/output/branch-javadoc-phoenix5-connectors-assembly.txt |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/5/artifact/yetus-general-check/output/diff-checkstyle-root.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/5/artifact/yetus-general-check/output/diff-javadoc-javadoc-root.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/5/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/5/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/5/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 1674 (vs. ulimit of 30000) |
| modules | C: phoenix-hive-base phoenix-hive-base/phoenix4-hive phoenix-hive-base/phoenix5-hive phoenix5-connectors-assembly . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/5/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 19s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   8m 59s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 37s |  master passed  |
| +1 :green_heart: |  compile  |   2m 30s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 21s |  master passed  |
| -1 :x: |  javadoc  |   0m 13s |  phoenix5-connectors-assembly in master failed.  |
| +0 :ok: |  spotbugs  |   5m 13s |  root in master has 116 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   1m 39s |  phoenix-hive-base in master has 46 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   0m 49s |  phoenix-hive-base/phoenix4-hive in master has 46 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   1m  2s |  phoenix-hive-base/phoenix5-hive in master has 45 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 35s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  12m 59s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 40s |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 40s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m 25s |  root: The patch generated 103 new + 0 unchanged - 0 fixed = 103 total (was 0)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  7s |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   0m 57s |  root generated 6 new + 14 unchanged - 6 fixed = 20 total (was 20)  |
| +1 :green_heart: |  spotbugs  |   9m  8s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  58m 13s |  root in the patch failed.  |
| -1 :x: |  asflicense  |   0m 45s |  The patch generated 2 ASF License warnings.  |
|  |   | 121m 49s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.hive.query.PhoenixQueryBuilderTest |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/6/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix-connectors/pull/42 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile spotbugs hbaseanti checkstyle |
| uname | Linux 4f80732f5412 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-connectors-personality.sh |
| git revision | master / 234ed7c |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/6/artifact/yetus-general-check/output/branch-javadoc-phoenix5-connectors-assembly.txt |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/6/artifact/yetus-general-check/output/diff-checkstyle-root.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/6/artifact/yetus-general-check/output/diff-javadoc-javadoc-root.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/6/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/6/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/6/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 1675 (vs. ulimit of 30000) |
| modules | C: phoenix-hive-base phoenix-hive-base/phoenix4-hive phoenix-hive-base/phoenix5-hive phoenix5-connectors-assembly . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/6/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   2m 13s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   9m 31s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   9m 54s |  master passed  |
| +1 :green_heart: |  compile  |   2m 35s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 21s |  master passed  |
| -1 :x: |  javadoc  |   0m 14s |  phoenix5-connectors-assembly in master failed.  |
| +0 :ok: |  spotbugs  |   5m 15s |  root in master has 116 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   1m 40s |  phoenix-hive-base in master has 46 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   0m 48s |  phoenix-hive-base/phoenix4-hive in master has 46 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   0m 56s |  phoenix-hive-base/phoenix5-hive in master has 45 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 36s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  16m 44s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m  8s |  the patch passed  |
| +1 :green_heart: |  javac  |   3m  8s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m 29s |  root: The patch generated 103 new + 0 unchanged - 0 fixed = 103 total (was 0)  |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  7s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  yamllint  |   0m  2s |  There were no new yamllint issues.  |
| -1 :x: |  javadoc  |   1m  4s |  root generated 6 new + 14 unchanged - 6 fixed = 20 total (was 20)  |
| +1 :green_heart: |  spotbugs  |  10m 26s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  55m 50s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 38s |  The patch does not generate ASF License warnings.  |
|  |   | 127m 54s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/7/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix-connectors/pull/42 |
| Optional Tests | dupname asflicense yamllint javac javadoc unit xml compile spotbugs hbaseanti checkstyle |
| uname | Linux ef4e9831bd02 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-connectors-personality.sh |
| git revision | master / 234ed7c |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/7/artifact/yetus-general-check/output/branch-javadoc-phoenix5-connectors-assembly.txt |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/7/artifact/yetus-general-check/output/diff-checkstyle-root.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/7/artifact/yetus-general-check/output/diff-javadoc-javadoc-root.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/7/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/7/testReport/ |
| Max. process+thread count | 1635 (vs. ulimit of 30000) |
| modules | C: phoenix-hive-base phoenix-hive-base/phoenix4-hive phoenix-hive-base/phoenix5-hive phoenix5-connectors-assembly . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/7/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 yamllint=1.20.0 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   2m 21s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   8m 52s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 55s |  master passed  |
| +1 :green_heart: |  compile  |   2m 54s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 22s |  master passed  |
| -1 :x: |  javadoc  |   0m 15s |  phoenix5-connectors-assembly in master failed.  |
| +0 :ok: |  spotbugs  |   5m 15s |  root in master has 116 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   1m 57s |  phoenix-hive-base in master has 46 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   0m 57s |  phoenix-hive-base/phoenix4-hive in master has 46 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   1m  2s |  phoenix-hive-base/phoenix5-hive in master has 45 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 35s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  15m  8s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m  2s |  the patch passed  |
| +1 :green_heart: |  javac  |   3m  2s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m 30s |  root: The patch generated 103 new + 0 unchanged - 0 fixed = 103 total (was 0)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  7s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  yamllint  |   0m  1s |  There were no new yamllint issues.  |
| -1 :x: |  javadoc  |   0m 59s |  root generated 6 new + 14 unchanged - 6 fixed = 20 total (was 20)  |
| +1 :green_heart: |  spotbugs  |  10m 30s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  64m 47s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 44s |  The patch does not generate ASF License warnings.  |
|  |   | 134m 51s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.kafka.PhoenixConsumerIT |
|   | phoenix.kafka.PhoenixConsumerIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/8/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix-connectors/pull/42 |
| Optional Tests | dupname asflicense yamllint javac javadoc unit xml compile spotbugs hbaseanti checkstyle |
| uname | Linux 84e365057cb5 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-connectors-personality.sh |
| git revision | master / 234ed7c |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/8/artifact/yetus-general-check/output/branch-javadoc-phoenix5-connectors-assembly.txt |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/8/artifact/yetus-general-check/output/diff-checkstyle-root.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/8/artifact/yetus-general-check/output/diff-javadoc-javadoc-root.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/8/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/8/testReport/ |
| Max. process+thread count | 1665 (vs. ulimit of 30000) |
| modules | C: phoenix-hive-base phoenix-hive-base/phoenix4-hive phoenix-hive-base/phoenix5-hive phoenix5-connectors-assembly . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-42/8/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 yamllint=1.20.0 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
