### PR TITLE
PHOENIX-6478 Exclude pentaho-aggdesigner-algorithm since it is not required and not available at Maven Central

### PR DESCRIPTION
**Pull request by martin-g**

### CODE REVIEW

**Comment by richardantal** [comment]
Please move the newly added repositories section to phoenix-hive-base, this way the phoenix4-hive-shaded module would still fail with the same error.
Otherwise it looks good.

**Comment by martin-g** [comment]
Thanks for the review, @richardantal !
I've pushed the change!

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   6m 33s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |  11m  8s |  Maven dependency ordering for branch  |
| -1 :x: |  mvninstall  |  19m  8s |  root in master failed.  |
| -1 :x: |  compile  |   0m 37s |  phoenix-hive-base in master failed.  |
| -1 :x: |  compile  |   0m 11s |  phoenix4-hive in master failed.  |
| -1 :x: |  javadoc  |   0m 14s |  phoenix-hive-base in master failed.  |
| -1 :x: |  javadoc  |   0m 11s |  phoenix4-hive in master failed.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 50s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |  22m 32s |  root in the patch failed.  |
| -1 :x: |  compile  |   1m 59s |  phoenix-hive-base in the patch failed.  |
| -1 :x: |  compile  |   1m 40s |  phoenix4-hive in the patch failed.  |
| -1 :x: |  javac  |   1m 59s |  phoenix-hive-base in the patch failed.  |
| -1 :x: |  javac  |   1m 40s |  phoenix4-hive in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  3s |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   1m 42s |  phoenix-hive-base in the patch failed.  |
| -1 :x: |  javadoc  |   1m 40s |  phoenix4-hive in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  17m 51s |  phoenix-hive-base in the patch failed.  |
| -1 :x: |  unit  |   1m 40s |  phoenix4-hive in the patch failed.  |
| -1 :x: |  asflicense  |   0m 16s |  The patch generated 1 ASF License warnings.  |
|  |   |  92m 43s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix-connectors/pull/53 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux 0a3177da7b26 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-connectors-personality.sh |
| git revision | master / a883279 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/artifact/yetus-general-check/output/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/artifact/yetus-general-check/output/branch-compile-phoenix-hive-base.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/artifact/yetus-general-check/output/branch-compile-phoenix-hive-base_phoenix4-hive.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/artifact/yetus-general-check/output/branch-javadoc-phoenix-hive-base.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/artifact/yetus-general-check/output/branch-javadoc-phoenix-hive-base_phoenix4-hive.txt |
| mvninstall | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/artifact/yetus-general-check/output/patch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/artifact/yetus-general-check/output/patch-compile-phoenix-hive-base.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/artifact/yetus-general-check/output/patch-compile-phoenix-hive-base_phoenix4-hive.txt |
| javac | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/artifact/yetus-general-check/output/patch-compile-phoenix-hive-base.txt |
| javac | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/artifact/yetus-general-check/output/patch-compile-phoenix-hive-base_phoenix4-hive.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/artifact/yetus-general-check/output/patch-javadoc-phoenix-hive-base.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/artifact/yetus-general-check/output/patch-javadoc-phoenix-hive-base_phoenix4-hive.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/artifact/yetus-general-check/output/patch-unit-phoenix-hive-base.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/artifact/yetus-general-check/output/patch-unit-phoenix-hive-base_phoenix4-hive.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 1793 (vs. ulimit of 30000) |
| modules | C: phoenix-hive-base phoenix-hive-base/phoenix4-hive U: phoenix-hive-base |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/2/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   6m 34s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |  11m 50s |  Maven dependency ordering for branch  |
| -1 :x: |  mvninstall  |  16m 34s |  root in master failed.  |
| -1 :x: |  compile  |   0m 31s |  phoenix-hive-base in master failed.  |
| -1 :x: |  compile  |   0m  9s |  phoenix4-hive in master failed.  |
| -1 :x: |  javadoc  |   0m 11s |  phoenix-hive-base in master failed.  |
| -1 :x: |  javadoc  |   0m  9s |  phoenix4-hive in master failed.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  20m 25s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 35s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 35s |  the patch passed  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  xml  |   0m  3s |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   0m 22s |  phoenix-hive-base generated 6 new + 0 unchanged - 0 fixed = 6 total (was 0)  |
| -1 :x: |  javadoc  |   0m 15s |  phoenix-hive-base_phoenix4-hive generated 3 new + 0 unchanged - 0 fixed = 3 total (was 0)  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  50m 12s |  phoenix-hive-base in the patch failed.  |
| +1 :green_heart: |  unit  |  28m 11s |  phoenix4-hive in the patch passed.  |
| -1 :x: |  asflicense  |   0m 15s |  The patch generated 2 ASF License warnings.  |
|  |   | 137m 59s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/3/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix-connectors/pull/53 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux ca1f0dcc5866 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-connectors-personality.sh |
| git revision | master / a883279 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/3/artifact/yetus-general-check/output/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/3/artifact/yetus-general-check/output/branch-compile-phoenix-hive-base.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/3/artifact/yetus-general-check/output/branch-compile-phoenix-hive-base_phoenix4-hive.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/3/artifact/yetus-general-check/output/branch-javadoc-phoenix-hive-base.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/3/artifact/yetus-general-check/output/branch-javadoc-phoenix-hive-base_phoenix4-hive.txt |
| whitespace | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/3/artifact/yetus-general-check/output/whitespace-eol.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/3/artifact/yetus-general-check/output/diff-javadoc-javadoc-phoenix-hive-base.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/3/artifact/yetus-general-check/output/diff-javadoc-javadoc-phoenix-hive-base_phoenix4-hive.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/3/artifact/yetus-general-check/output/patch-unit-phoenix-hive-base.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/3/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/3/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 1895 (vs. ulimit of 30000) |
| modules | C: phoenix-hive-base phoenix-hive-base/phoenix4-hive U: phoenix-hive-base |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-53/3/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by stoty — APPROVED** [review]
+1 LGTM

**Comment by richardantal** [comment]
I merged this change.
Thanks for the fix @martin-g and for the review @stoty

**Pull request merged**
