### PR TITLE
PHOENIX-6945 Update Surefire plugin to 3.0.0 and switch to TCP forkNo…

### PR DESCRIPTION
**Pull request by stoty**
…de implementation

### CODE REVIEW

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   3m 48s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  19m  8s |  master passed  |
| +1 :green_heart: |  compile  |   1m 17s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 26s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   7m 55s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 21s |  the patch passed  |
| -1 :x: |  javac  |   1m 21s |  root generated 42 new + 2082 unchanged - 42 fixed = 2124 total (was 2124)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   0m 28s |  root generated 42 new + 2095 unchanged - 42 fixed = 2137 total (was 2137)  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  33m 16s |  root in the patch failed.  |
| -1 :x: |  asflicense  |   0m  8s |  The patch generated 3 ASF License warnings.  |
|  |   |  68m  6s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-106/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix-connectors/pull/106 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux e708d73eb918 4.15.0-212-generic #223-Ubuntu SMP Tue May 23 13:09:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-connectors-personality.sh |
| git revision | master / 7e3bc08 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| javac | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-106/1/artifact/yetus-general-check/output/diff-compile-javac-root.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-106/1/artifact/yetus-general-check/output/diff-javadoc-javadoc-root.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-106/1/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-106/1/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-106/1/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 1902 (vs. ulimit of 30000) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-Connectors-PreCommit-GitHub-PR/job/PR-106/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by richardantal — APPROVED** [review]
LGTM

**Review by richardantal — CHANGES_REQUESTED** [review]
On second thought it looks like the maven-surefire-plugin.version is not beeing used

**Comment by stoty** [comment]
I messed up and applied the wrong patch.
I have pushed an addenum to fix the problem you have found.

**Pull request closed without merging**
